### PR TITLE
Adding provision to add profile photo with responsive layout

### PR DESCRIPTION
**Pull request by khushChopra**
The template did not provide a way to add a profile photo for better connection to visitors.

This is definitely subjective, would love to discuss it if needed. Will leave the final judgement to the owner of the repo.

### CODE REVIEW

**Comment by khushChopra** [comment]
For reference - https://choprakhush.com/

**Comment by MaeWolff** [comment]
@khushChopra Good idea for those who want to add an image.
We could add the image link to the `presentation.ts` file and make it optional. What do you think?

**Comment by khushChopra** [comment]
That would be the way to go. I will make that change.

**Comment by MaeWolff** [comment]
nice!! Thanks for your contribution and idea :) Can you rebase your branch with the main branch please?

**Pull request merged**
